# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NQcMEMNc0736ukbaxEdaEFOx1JZAIXNZ
"""

import pandas as pd
data = {
    "Name": [
        "Abel", "Sara", "John", "Mimi", "David",
        "Liya", "Noah", "Hana", "Eden", "Samuel",
        "Ruth", "Daniel", "Rahel", "Ben", "Helen"
    ],
    "Age": [20, 21, 19, 22, 23, 20, 21, 22, 19, 23, 20, 21, 22, 19, 23],
    "Department": [
        "CS", "SE", "IT", "CS", "SE",
        "IT", "CS", "SE", "IT", "CS",
        "SE", "IT", "CS", "SE", "IT"
    ],
    "GPA": [3.5, 3.7, 3.2, 3.8, 3.6, 3.4, 3.9, 3.3, 3.1, 3.7, 3.5, 3.6, 3.8, 3.2, 3.4],
    "Graduated": [
        False, False, False, False, True,
        False, True, False, False, True,
        False, True, False, False, True
    ]
}
index_labels = [f"STD{i}" for i in range(1, 16)]

df = pd.DataFrame(data, index=index_labels)

print(df)

df = pd.read_csv("Titanic-Dataset.csv")

df.head()

df.info()

df.describe()

df = pd.read_csv("Titanic-Dataset.csv")

# Handle missing values (correct way)
df["Age"] = df["Age"].fillna(df["Age"].median())
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])

# Drop Cabin
df = df.drop("Cabin", axis=1)

# Remove duplicates
df = df.drop_duplicates()

# Check
print(df.isnull().sum())
print(df.shape)

"""After cleaning the dataset, all missing values were handled, the Cabin column was removed due to excessive null values, and the dataset contains 891 rows and 11 columns with no missing data remaining."""

survival_gender = df.groupby("Sex")["Survived"].mean()
print(survival_gender)

"""Groups by Sex
Calculates average of Survived (0 = died, 1 = survived)
"""

survival_class = df.groupby("Pclass")["Survived"].mean()
print(survival_class)

"""Higher class → higher survival chance"""

avg_age_class = df.groupby("Pclass")["Age"].mean()
print(avg_age_class)

df["AgeGroup"] = pd.cut(
    df["Age"],
    bins=[0, 12, 18, 35, 60, 100],
    labels=["Child", "Teen", "Young Adult", "Adult", "Senior"]
)

survival_age_group = df.groupby("AgeGroup")["Survived"].mean()
print(survival_age_group)

"""✔ Gender: Females had a significantly higher survival rate than males.
✔ Class: Passengers in higher classes (1st class) had better survival chances.
✔ Age: Younger passengers (children) had higher survival rates compared to older passengers.
"""

df.groupby(["Sex", "Pclass"])["Survived"].mean()

"""Female Passengers Who Survived"""

female_survived = df[(df["Sex"] == "female") & (df["Survived"] == 1)]

print(female_survived.head())

"""Childrens who servived"""

children_survived = df[(df["AgeGroup"] == "Child") & (df["Survived"] == 1)]

print(children_survived.head())

"""1st Class Passengers with High Survival Probability"""

first_class_survived = df[(df["Pclass"] == 1) & (df["Survived"] == 1)]

print(first_class_survived.head())

"""# ***Insight***

1.Who was more likely to survive? (Gender)

Females were significantly more likely to survive than males.

Survival rate of females is much higher (around 70–75%)
Males had a much lower survival rat (~15–20%)

2.Did class affect survival?

Yes, passenger class had a strong impact on survival.

1st class → highest survival rate

2nd class → moderate

3rd class → lowest

Wealthier passengers had:
 - Better cabin locations
 - Faster access to lifeboats

3. Were children prioritized?

Yes, children had a higher survival rate compared to many adults.
Children (especially under ~12) show higher survival rates
They were prioritized during evacuation

4. What combination had the highest survival rate?

Female passengers in 1st class had the highest survival rate.
Being female + 1st class = highest chance of survival

Worst-case combination:
 - Male + 3rd class → lowest survival rate

The analysis shows that survival on the Titanic was strongly influenced by gender, passenger class, and age. Females and children were prioritized, and higher-class passengers had better access to safety. The highest survival rates were observed among first-class female passengers, while third-class males had the lowest chances of survival.
"""